-- CreateTable
CREATE TABLE "Play" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "mediaType" TEXT NOT NULL,
    "tmdbId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "poster" TEXT,
    "seasonNumber" INTEGER,
    "episodeNumber" INTEGER,
    "episodeName" TEXT,
    "runtime" INTEGER NOT NULL DEFAULT 0,
    "watchedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "sourceRef" TEXT,
    CONSTRAINT "Play_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_WatchedEpisode" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "showId" INTEGER NOT NULL,
    "showName" TEXT NOT NULL,
    "showPoster" TEXT,
    "seasonNumber" INTEGER NOT NULL,
    "episodeNumber" INTEGER NOT NULL,
    "episodeName" TEXT NOT NULL,
    "runtime" INTEGER NOT NULL DEFAULT 42,
    "watchedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastWatchedAt" DATETIME,
    "plays" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "WatchedEpisode_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_WatchedEpisode" ("episodeName", "episodeNumber", "id", "runtime", "seasonNumber", "showId", "showName", "showPoster", "userId", "watchedAt") SELECT "episodeName", "episodeNumber", "id", "runtime", "seasonNumber", "showId", "showName", "showPoster", "userId", "watchedAt" FROM "WatchedEpisode";
DROP TABLE "WatchedEpisode";
ALTER TABLE "new_WatchedEpisode" RENAME TO "WatchedEpisode";
CREATE INDEX "WatchedEpisode_userId_watchedAt_idx" ON "WatchedEpisode"("userId", "watchedAt");
CREATE UNIQUE INDEX "WatchedEpisode_userId_showId_seasonNumber_episodeNumber_key" ON "WatchedEpisode"("userId", "showId", "seasonNumber", "episodeNumber");
CREATE TABLE "new_WatchedMovie" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "movieId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "poster" TEXT,
    "runtime" INTEGER NOT NULL DEFAULT 0,
    "score" INTEGER,
    "watchedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastWatchedAt" DATETIME,
    "plays" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "WatchedMovie_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_WatchedMovie" ("id", "movieId", "poster", "runtime", "score", "title", "userId", "watchedAt") SELECT "id", "movieId", "poster", "runtime", "score", "title", "userId", "watchedAt" FROM "WatchedMovie";
DROP TABLE "WatchedMovie";
ALTER TABLE "new_WatchedMovie" RENAME TO "WatchedMovie";
CREATE INDEX "WatchedMovie_userId_watchedAt_idx" ON "WatchedMovie"("userId", "watchedAt");
CREATE UNIQUE INDEX "WatchedMovie_userId_movieId_key" ON "WatchedMovie"("userId", "movieId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "Play_userId_watchedAt_idx" ON "Play"("userId", "watchedAt");

-- CreateIndex
CREATE INDEX "Play_userId_mediaType_tmdbId_watchedAt_idx" ON "Play"("userId", "mediaType", "tmdbId", "watchedAt");

-- CreateIndex
CREATE UNIQUE INDEX "Play_userId_source_sourceRef_key" ON "Play"("userId", "source", "sourceRef");

-- Backfill: one play per row already on record, so that adding the log does not
-- retroactively halve anyone's history.
--
-- The ids are synthetic rather than cuids because cuid() is generated by the
-- Prisma client, not by SQLite. These are plain TEXT primary keys with no format
-- constraint anywhere in the codebase, and deriving them from the source row's
-- id keeps them stable if this ever has to be re-run.
--
-- `sourceRef` is left null on every row: SQLite treats nulls as distinct in a
-- unique index, so thousands of them coexist happily under
-- Play_userId_source_sourceRef_key. A sentinel string here would fail on row two.
INSERT INTO "Play" ("id", "userId", "mediaType", "tmdbId", "title", "poster",
                    "seasonNumber", "episodeNumber", "episodeName", "runtime",
                    "watchedAt", "source", "sourceRef")
SELECT 'bf_m_' || "id", "userId", 'movie', "movieId", "title", "poster",
       NULL, NULL, NULL, "runtime", "watchedAt", 'backfill', NULL
FROM "WatchedMovie";

INSERT INTO "Play" ("id", "userId", "mediaType", "tmdbId", "title", "poster",
                    "seasonNumber", "episodeNumber", "episodeName", "runtime",
                    "watchedAt", "source", "sourceRef")
SELECT 'bf_e_' || "id", "userId", 'tv', "showId", "showName", "showPoster",
       "seasonNumber", "episodeNumber", "episodeName", "runtime",
       "watchedAt", 'backfill', NULL
FROM "WatchedEpisode";

-- Everything on record so far is exactly one viewing, first and last alike.
UPDATE "WatchedMovie"   SET "plays" = 1, "lastWatchedAt" = "watchedAt";
UPDATE "WatchedEpisode" SET "plays" = 1, "lastWatchedAt" = "watchedAt";
